name: Meson Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: python3 -m pip install meson ninja
    - run: meson builddir
    - run: ninja -C builddir
